config:
	python3.10 -m venv ../../../.venv && \
	sh ../../../.venv/bin/activate && \
	pip install -r ../../../requirements.txt

run:
	sh ../../../.venv/bin/activate && \
	python3.10 main.py

PHONY.: config run